services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=github_trending
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_trending"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # Ports removed to force traffic through Nginx. 
    # Uncomment the next two lines if you still want direct access via port 4000:
    # ports:
    #   - "4000:4000"
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=github_trending
      - PGUSER=postgres
      - PGPASSWORD=password
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SYNC_DATA_ON_STARTUP=false
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  postgres_data: