services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=github_trending
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_trending"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=github_trending
      - PGUSER=postgres
      - PGPASSWORD=password
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SYNC_DATA_ON_STARTUP=false
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:ro       # Read access to challenge files
      - ./certbot/conf:/etc/letsencrypt:ro      # Read access to certificates
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw       # Write access to challenge files
      - ./certbot/conf:/etc/letsencrypt:rw      # Write access to certificates

volumes:
  postgres_data: